name: Auto-format C++ Code

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

permissions:
  contents: write
  pull-requests: write

jobs:
  format:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
      
      - name: Format C++ code
        uses: pachadotdev/clang-format@main
        with:
          version: '18'
          auto-commit: true
          commit-message: 'style: auto-format C++ code with clang-format-18'
